heat_template_version: 2015-10-15
description: Launch a basic instance with Ubuntu Xenial image using the
             ``2048-10-1-1`` flavor, ``daniel`` key,  and one network.

parameters:
  NetID:
    type: string
    description: 10ec556ab-d458-470e-96bc-1bab0ef66fb9
    

resources:
  server:
    type: OS::Nova::Server
    properties:
      image: xenial-server-cloudimg-amd64-disk1
      flavor: 2048-10-1-1
      key_name: CQ
      networks: 
      - network: { get_param: NetID }
      user_data_format: RAW
      user_data: |
        #!/bin/bash
        sudo -i
        echo "update system because because python2.7 doesnt seem to be installed"
        apt update
        apt-get upgrade
        echo "install python"
        apt-get --assume-yes --fix-missing install python2.7
        echo "check python2.7 version" 
        python2.7 --version
        echo "getting server.py"
        wget https://raw.githubusercontent.com/houssemmh/INF8480-TP3/master/server.py
        echo "starting server.py"
        python2.7 server.py&
        echo "server script started"
        # ...

outputs:
  instance_name:
    description: Name of the instance.
    value: { get_attr: [ server, name ] }
  instance_ip:
    description: IP address of the instance.
    value: { get_attr: [ server, first_address ] }

   
