heat_template_version: 2015-10-15
description: Launch a basic instance with Ubuntu Xenial image using the
             ``2048-10-1-1`` flavor, ``daniel`` key,  and one network.

parameters:
  NetID:
    type: string
    description: Network ID to use for the instance.

resources:
  server:
    type: OS::Nova::Server
    properties:
      image: xenial-server-cloudimg-amd64-disk1
      flavor: 2048-10-1-1
      key_name: daniel
      networks:
      - network: { get_param: NetID }
      user_data: { get_file: https://raw.githubusercontent.com/houssemmh/INF8480-TP3/master/server.py }
      cloud_config: 
        runcmd:
            - echo "This is a test runCMD"
        bootcmd:
            - echo "Boot is complete testing" 

outputs:
  instance_name:
    description: Name of the instance.
    value: { get_attr: [ server, name ] }
  instance_ip:
    description: IP address of the instance.
    value: { get_attr: [ server, first_address ] }

